### ISSUE TITLE
IPageService, INavigationAware, INavigableView not found (4.0.2-rc)

### ISSUE THREAD

**Issue by nandaccio** [lepoco/wpfui#1278]
### Describe the bug

Version 4.0.2-rc breaks existing code based on the WPUI template. I looked for information about breaking changes on https://github.com/lepoco/wpfui/releases and the main page of the repo, I also installed:

    <PackageReference Include="WPF-UI.Abstractions" Version="4.0.0-rc.2" />
    <PackageReference Include="WPF-UI.DependencyInjection" Version="4.0.0-rc.2" />

But I can no longer compile the project because of several errors:

- IPageService is not available
- INavigationAware is not available
- INavigableView is not available
- NavigationView does not contain a definition of SetPageService
- MainWindow does not implement INavigationWindow.SetPageService
etc

### To Reproduce

Update a simple project based on the official templates for 3.x to use 4.x (including WPF-UI.Abstractions)

Workaround:
Revert to 
```
  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="3.0.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0-preview2" />
  </ItemGroup>
```
### Expected behavior

Breaking changes should be documented, 

### OS version

Windows 11

### .NET version

.NET 8

### WPF-UI NuGet version

 <ItemGroup>
   <PackageReference Include="WPF-UI" Version="4.0.0-rc.2" />
   <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
   <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0-preview2" />
   <PackageReference Include="WPF-UI.Abstractions" Version="4.0.0-rc.2" />
   <PackageReference Include="WPF-UI.DependencyInjection" Version="4.0.0-rc.2" />
 </ItemGroup>

**Comment by khimoc97** [comment]
Me also got the issue when upgrade from 3.0.5 to 4.0.0-rc.2
![image](https://github.com/user-attachments/assets/aecce7a2-7415-47a3-8d05-0346964da0b5)

**Comment by nabeelio** [comment]
Same, on the release version. The docs also still show `IPageService` still being used

**Comment by nabeelio** [comment]
I guess it's called `INavigationViewPageProvider` now?

**Comment by nabeelio** [comment]
Yep,

- `IPageService` -> `INavigationViewPageProvider` - reimplement the interface

```
- NavigationControl.SetPageService(_pageService);
- +NavigationControl.SetPageProviderService(_pageService);
```

**Comment by BorisovskiP** [comment]
I also get this issue in the 4.0.0 release. Have to revert to version 3.0.5 to have my app working again. @pomianowski is there any documentation on what changed here?

**Comment by pomianowski** [comment]
Hey! The main changes in version 4.0.0, including the updates to navigation, are outlined here: https://wpfui.lepo.co/migration/v4-migration.html
